- name: To Configure the frontend service
  hosts: frontend
  become: yes
  tasks:

  - name: To install web server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: To enable and restart the service
    ansible.builtin.service:
      name: nginx
      state: present
      enabled: yes
  
  - name: to remove deafault content in html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: to create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend source code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense.conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted