- name: MySQL playbook
  hosts: mysql
  become: yes
  tasks:
  - name: To install mysql DB on server
    ansible.builtin.package:
      name: mysql
      state: installed

  - name: To enable and start the mysql service
    ansible.builtin.service:
      enabled: yes
      name: mysql
      state: start 
